### ISSUE TITLE
Team name doesn't autofill

### ISSUE THREAD

**Issue by AarushPalve** [sjcbulldog/xeroscout#31]
When a scouter selects a match to scout the team they have to scout doesn't display.

**Comment by sjcbulldog** [comment]
Actually I am not sure why we have a team number field in the scouting form.  The number is already part of the scouting data that gets sent to the scouting central machine.  However, we do not display the team number on the scouting tablet.  Maybe what we really need is up at the top where we show "Qual Match, Match 2", that we also put the team number so it is easy to read and see?

**Comment by suhaaniii** [comment]
Yes, I agree that it's not necessary to have the team number field. We have that there because the team number isn't displayed on the interface after you click a match, so scouters often forget the team they're scouting. Like you said, it would be beneficial to have the team number displayed at the top for easy access. This is what my other Github issue is referring to so you can disregard that.
